### ISSUE TITLE
CurrencyEditText crashes on init

### ISSUE THREAD

**Issue by javierpe** [faranjit/currency_edittext#1]
Please in CurrencyEditText.java validate if getText().toString() is empty for prevent crashes.

    /***
     *It resets text currently displayed If user changes separators or locale etc.
     */
    private void resetText() {
        String s = getText().toString();
        if(!s.isEmpty()) {
            s = s.replace(groupDivider, '\u0020').replace(monetaryDivider, '\u0020')
                    .replace(".", "").replace(" ", "")
                    .replace(currencySymbol, "").trim();
            try {
                initSettings();
                s = format(s);
                removeTextChangedListener(onTextChangeListener);
                setText(s);
                setSelection(s.length());
                addTextChangedListener(onTextChangeListener);
            } catch (ParseException e) {
                Log.e(getClass().getCanonicalName(), e.getMessage());
            }
        }
    }

Regards!

**Comment by faranjit** [comment]
Thank you for suggestion. I pushed a new branch and merged it to master.
