### ISSUE TITLE
Set number of decimal places

### ISSUE THREAD

**Issue by iScripters** [faranjit/currency_edittext#5]
Hi, I would like the option to set the number of decimals, for example `setDecimals(4);` would allow 0.0000 instead of only 0.00

Could this be added?

**Comment by Zulqarnain-Mustafa** [comment]
Or May setting the Decimal to zero. `setDecimals(0);`

**Comment by faranjit** [comment]
Hi,
I tried to add your suggestions. Please see [this commit](https://github.com/faranjit/currency_edittext/commit/3ecbb07ea684be391535ea783d08ddabaf2b79dd).

**Comment by lucasrafagnin** [comment]
Hi @faranjit , this [commit](https://github.com/faranjit/currency_edittext/commit/3ecbb07ea684be391535ea783d08ddabaf2b79dd) is included in the latest release? Because I tried the 1.0.1 version and it don't have the `decimalPoints` option.

**Comment by adeds** [comment]
Hi @faranjit , this commit is included in the latest release? Because I tried the 1.0.1 version and it don't have the decimalPoints option. (2)

**Comment by faranjit** [comment]
Hi, 1.0.1 is outdated. There is no new version. Please, can you take the source code and use it?
